import { Poppins} from "next/font/google";
import "./globals.css";



const fontPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Calango Estamparia",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
